#ifndef QDP_CONFIG_H
#define QDP_CONFIG_H


/* Undef the unwanted from the environment -- eg the compiler command line */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

/* Include the stuff generated by autoconf */
#include "qdp_config_internal.h"

/* Prefix everything with QDP_ */
#define QDP_PACKAGE PACKAGE
#define QDP_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#define QDP_PACKAGE_NAME PACKAGE_NAME
#define QDP_PACKAGE_STRING PACKAGE_STRING
#define QDP_PACKAGE_TARNAME PACKAGE_TARNAME
#define QDP_PACKAGE_VERSION PACKAGE_VERSION
#define QDP_VARSION VERSION


/* Undef the unwanted */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION
#endif
